type = "toml"
orphan = [
  "red",
  "blue",
  "orange"
]
bools = [
  true,
  false,
  true
]
intbools = [
  1.0,
  0.0,
  1.0
]
strbools = [
  "1",
  "t",
  "f"
]
strbool = "1"
time = "2019-01-01"
duration = "3s"
negative_int = -1234

[parent1]
name = "parent1"
id = 1234.0

  [parent1.child1]
  name = "child1"
  type = "toml"

    [parent1.child1.grandchild1]
    ids = [
      1.0,
      2.0,
      3.0
    ]
    on = true

    [parent1.child1.empty]

  [parent1.strmap]
  key1 = "val1"
  key2 = "val2"
  key3 = "val3"

  [parent1.strsmap]
  key1 = [
    "val1",
    "val2",
    "val3"
  ]
  key2 = [
    "val4",
    "val5"
  ]

  [parent1.intmap]
  key1 = 1.0
  key2 = 1.0
  key3 = 1.0

  [parent1.floatmap]
  key1 = 1.1
  key2 = 1.2
  key3 = 1.3

  [parent1.boolmap]
  ok1 = true
  ok2 = true
  notok3 = false

[parent2]
name = "parent2"
id = 5678.0

  [parent2.child2]
  name = "child2"

    [parent2.child2.grandchild2]
    ids = [
      4.0,
      5.0,
      6.0
    ]
    on = true

    [parent2.child2.empty]

[empty]
